// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ComputeECDF
NumericMatrix ComputeECDF(NumericVector rank_x, NumericVector rank_y, IntegerVector NR_Atoms);
RcppExport SEXP _HHG_ComputeECDF(SEXP rank_xSEXP, SEXP rank_ySEXP, SEXP NR_AtomsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type rank_x(rank_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rank_y(rank_ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type NR_Atoms(NR_AtomsSEXP);
    rcpp_result_gen = Rcpp::wrap(ComputeECDF(rank_x, rank_y, NR_Atoms));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_Compute_ADP_MAX_3X3_over_atoms
List rcpp_Compute_ADP_MAX_3X3_over_atoms(NumericVector rank_x, NumericVector rank_y, IntegerVector NR_Atoms, IntegerVector Wmax);
RcppExport SEXP _HHG_rcpp_Compute_ADP_MAX_3X3_over_atoms(SEXP rank_xSEXP, SEXP rank_ySEXP, SEXP NR_AtomsSEXP, SEXP WmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type rank_x(rank_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rank_y(rank_ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type NR_Atoms(NR_AtomsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Wmax(WmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_Compute_ADP_MAX_3X3_over_atoms(rank_x, rank_y, NR_Atoms, Wmax));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_Compute_ADP_MAX_3X2_over_atoms
List rcpp_Compute_ADP_MAX_3X2_over_atoms(NumericVector rank_x, NumericVector rank_y, IntegerVector NR_Atoms, IntegerVector Wmax);
RcppExport SEXP _HHG_rcpp_Compute_ADP_MAX_3X2_over_atoms(SEXP rank_xSEXP, SEXP rank_ySEXP, SEXP NR_AtomsSEXP, SEXP WmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type rank_x(rank_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rank_y(rank_ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type NR_Atoms(NR_AtomsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Wmax(WmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_Compute_ADP_MAX_3X2_over_atoms(rank_x, rank_y, NR_Atoms, Wmax));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_Compute_ADP_MAX_2X2_over_atoms
List rcpp_Compute_ADP_MAX_2X2_over_atoms(NumericVector rank_x, NumericVector rank_y, IntegerVector NR_Atoms, IntegerVector Wmax);
RcppExport SEXP _HHG_rcpp_Compute_ADP_MAX_2X2_over_atoms(SEXP rank_xSEXP, SEXP rank_ySEXP, SEXP NR_AtomsSEXP, SEXP WmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type rank_x(rank_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rank_y(rank_ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type NR_Atoms(NR_AtomsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Wmax(WmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_Compute_ADP_MAX_2X2_over_atoms(rank_x, rank_y, NR_Atoms, Wmax));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP HHG_R_C(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_HHG_ComputeECDF", (DL_FUNC) &_HHG_ComputeECDF, 3},
    {"_HHG_rcpp_Compute_ADP_MAX_3X3_over_atoms", (DL_FUNC) &_HHG_rcpp_Compute_ADP_MAX_3X3_over_atoms, 4},
    {"_HHG_rcpp_Compute_ADP_MAX_3X2_over_atoms", (DL_FUNC) &_HHG_rcpp_Compute_ADP_MAX_3X2_over_atoms, 4},
    {"_HHG_rcpp_Compute_ADP_MAX_2X2_over_atoms", (DL_FUNC) &_HHG_rcpp_Compute_ADP_MAX_2X2_over_atoms, 4},
    {"HHG_R_C", (DL_FUNC) &HHG_R_C, 16},
    {NULL, NULL, 0}
};

RcppExport void R_init_HHG(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
