# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ComputeECDF <- function(rank_x, rank_y, NR_Atoms) {
    .Call(`_HHG_ComputeECDF`, rank_x, rank_y, NR_Atoms)
}

rcpp_Compute_ADP_MAX_3X3_over_atoms <- function(rank_x, rank_y, NR_Atoms, Wmax) {
    .Call(`_HHG_rcpp_Compute_ADP_MAX_3X3_over_atoms`, rank_x, rank_y, NR_Atoms, Wmax)
}

rcpp_Compute_ADP_MAX_3X2_over_atoms <- function(rank_x, rank_y, NR_Atoms, Wmax) {
    .Call(`_HHG_rcpp_Compute_ADP_MAX_3X2_over_atoms`, rank_x, rank_y, NR_Atoms, Wmax)
}

rcpp_Compute_ADP_MAX_2X2_over_atoms <- function(rank_x, rank_y, NR_Atoms, Wmax) {
    .Call(`_HHG_rcpp_Compute_ADP_MAX_2X2_over_atoms`, rank_x, rank_y, NR_Atoms, Wmax)
}

